AppDir re-write with shadcn ui-components (#74)
* Initial commit to re-write

* install npx create next app with typescript

* Add shadcnui + recreate homepage

* add signin,signup pages + api routes + react-email for siginin with prisma

* add signin,signup pages + api routes + react-email for siginin with prisma

* Add signup. sigin email

* Fix no module issue

* Update calendar + select

* Add card summary + loader

* Adjust card + seperator style

* fix ts lint error

* Fix lint errors + add eslint prettier fixes

* Add feedback popover with shadcn ui

* Add auth check + fix feedback issue

* organise components

* organise components

* organise components

* Add table loading style

* add chart + recent table loader

* set session with auth-provider

* Add bar + donut chart to overview page

* add recent table data in overview

* ui tweaks

* Update toast + design tweaks

* add expense summary + tooltip ui

* Add expense modal + modify chart style

* Add expense modal + modify chart style

* Add shortcut

* Add modal for expenses

* Update data table style + sorting

* add tables for income, investments and expenses

* Add expenses table + export

* use swr for fetch to cache

* Fix this week and add swr for overview

* SOme changes to ui

* create a re-usable table components

* Add edit/add modal

* income + invesments done

* Add welcome email with some subscription fix

* Add welcome email with some subscription fix

* Fix prettier issue

* fix cal + add nextjs config

* add subscription modal

* add usage limit + email

* Add settins page

* Add settins page

* Add settins page

* add theme section in settings

* Add delete account api

* update currency style

* Update plan + email style

* Update delete section

* Add emails + limit usage emails

* fix homepage width issue

* Add payments + upgrade readme

* Fix DynamicServerError: Dynamic server usage: cookies error

* Add progress loader

* Fix cannot find module type issue

* fix env process

* add open graph + icons via appdir

* Add combo box for currency to search

* upgrade resend

* Refactor data-provider context with lookup changes

* add mobile menu bar

* add mobile menu bar

* Add error boundary

* test app

* test middleware

* add error.tsx

* Revert and fix sidebar